version: "3"

services:
  ollama:
    image: ghcr.io/nagaraj-real/ollama:mistral
    ports:
      - "11434:11434"
    networks:
      - llm-network
    volumes:
      - ollama:/root/.ollama
    container_name: ollama-container

  mongodb:
    image: ghcr.io/nagaraj-real/agent-builder-mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - llm-network

  agent-builder:
    image: ghcr.io/nagaraj-real/agent-builder-api:latest
    tty: true
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - llm-network
    container_name: agent-builder-container
    env_file: ./../.env
    environment:
      EXTRA_DEPS: "mongodb"
      OLLAMA_URL: "http://ollama:11434"
      UVICORN_OPTIONS: "--host 0.0.0.0 --port 8080 --log-level info --log-config /app/log_config.yml --workers 1 --reload --reload-dir /app --reload-include .env"
      MONGODB_URL: "mongodb://mongodb:27017/llmdb"
    command: ["/bin/sh", "-c", "while sleep 1000; do :; done"]

networks:
  llm-network:

volumes:
  dbdata:
